entrenadores = [
    # --- KANTO ---
    {'nombre': 'Brock', 'torneos_ganados': 1, 'batallas_perdidas': 45, 'batallas_ganadas': 105, 'pokemons': [{'nombre': 'Geodude', 'nivel': 12, 'tipo': 'Roca', 'subtipo': 'Tierra'}, {'nombre': 'Onix', 'nivel': 14, 'tipo': 'Roca', 'subtipo': 'Tierra'}]},
    {'nombre': 'Misty', 'torneos_ganados': 2, 'batallas_perdidas': 30, 'batallas_ganadas': 120, 'pokemons': [{'nombre': 'Staryu', 'nivel': 18, 'tipo': 'Agua', 'subtipo': None}, {'nombre': 'Starmie', 'nivel': 21, 'tipo': 'Agua', 'subtipo': 'Psíquico'}, {'nombre': 'Gyarados', 'nivel': 25, 'tipo': 'Agua', 'subtipo': 'Volador'}]},
    {'nombre': 'Lt. Surge', 'torneos_ganados': 1, 'batallas_perdidas': 50, 'batallas_ganadas': 150, 'pokemons': [{'nombre': 'Voltorb', 'nivel': 21, 'tipo': 'Eléctrico', 'subtipo': None}, {'nombre': 'Pikachu', 'nivel': 18, 'tipo': 'Eléctrico', 'subtipo': None}, {'nombre': 'Raichu', 'nivel': 24, 'tipo': 'Eléctrico', 'subtipo': None}]},
    {'nombre': 'Erika', 'torneos_ganados': 2, 'batallas_perdidas': 40, 'batallas_ganadas': 110, 'pokemons': [{'nombre': 'Victreebel', 'nivel': 29, 'tipo': 'Planta', 'subtipo': 'Veneno'}, {'nombre': 'Tangela', 'nivel': 24, 'tipo': 'Planta', 'subtipo': None}, {'nombre': 'Vileplume', 'nivel': 29, 'tipo': 'Planta', 'subtipo': 'Veneno'}]},
    {'nombre': 'Koga', 'torneos_ganados': 1, 'batallas_perdidas': 45, 'batallas_ganadas': 130, 'pokemons': [{'nombre': 'Koffing', 'nivel': 37, 'tipo': 'Veneno', 'subtipo': None}, {'nombre': 'Muk', 'nivel': 39, 'tipo': 'Veneno', 'subtipo': None}, {'nombre': 'Koffing', 'nivel': 37, 'tipo': 'Veneno', 'subtipo': None}, {'nombre': 'Weezing', 'nivel': 43, 'tipo': 'Veneno', 'subtipo': None}]},
    {'nombre': 'Sabrina', 'torneos_ganados': 3, 'batallas_perdidas': 20, 'batallas_ganadas': 180, 'pokemons': [{'nombre': 'Kadabra', 'nivel': 38, 'tipo': 'Psíquico', 'subtipo': None}, {'nombre': 'Mr. Mime', 'nivel': 37, 'tipo': 'Psíquico', 'subtipo': 'Hada'}, {'nombre': 'Venomoth', 'nivel': 38, 'tipo': 'Bicho', 'subtipo': 'Veneno'}, {'nombre': 'Alakazam', 'nivel': 43, 'tipo': 'Psíquico', 'subtipo': None}]},
    {'nombre': 'Blaine', 'torneos_ganados': 2, 'batallas_perdidas': 35, 'batallas_ganadas': 140, 'pokemons': [{'nombre': 'Growlithe', 'nivel': 42, 'tipo': 'Fuego', 'subtipo': None}, {'nombre': 'Ponyta', 'nivel': 40, 'tipo': 'Fuego', 'subtipo': None}, {'nombre': 'Rapidash', 'nivel': 42, 'tipo': 'Fuego', 'subtipo': None}, {'nombre': 'Arcanine', 'nivel': 47, 'tipo': 'Fuego', 'subtipo': None}]},
    {'nombre': 'Giovanni', 'torneos_ganados': 4, 'batallas_perdidas': 30, 'batallas_ganadas': 170, 'pokemons': [{'nombre': 'Rhyhorn', 'nivel': 45, 'tipo': 'Tierra', 'subtipo': 'Roca'}, {'nombre': 'Dugtrio', 'nivel': 42, 'tipo': 'Tierra', 'subtipo': None}, {'nombre': 'Nidoqueen', 'nivel': 44, 'tipo': 'Veneno', 'subtipo': 'Tierra'}, {'nombre': 'Nidoking', 'nivel': 45, 'tipo': 'Veneno', 'subtipo': 'Tierra'}, {'nombre': 'Rhydon', 'nivel': 50, 'tipo': 'Tierra', 'subtipo': 'Roca'}]},
    {'nombre': 'Blue', 'torneos_ganados': 7, 'batallas_perdidas': 15, 'batallas_ganadas': 250, 'pokemons': [{'nombre': 'Pidgeot', 'nivel': 61, 'tipo': 'Normal', 'subtipo': 'Volador'}, {'nombre': 'Alakazam', 'nivel': 59, 'tipo': 'Psíquico', 'subtipo': None}, {'nombre': 'Rhydon', 'nivel': 61, 'tipo': 'Tierra', 'subtipo': 'Roca'}, {'nombre': 'Exeggutor', 'nivel': 61, 'tipo': 'Planta', 'subtipo': 'Psíquico'}, {'nombre': 'Arcanine', 'nivel': 61, 'tipo': 'Fuego', 'subtipo': None}, {'nombre': 'Blastoise', 'nivel': 65, 'tipo': 'Agua', 'subtipo': None}]},
    
    # --- JOHTO ---
    {'nombre': 'Falkner', 'torneos_ganados': 1, 'batallas_perdidas': 40, 'batallas_ganadas': 80, 'pokemons': [{'nombre': 'Pidgey', 'nivel': 7, 'tipo': 'Normal', 'subtipo': 'Volador'}, {'nombre': 'Pidgeotto', 'nivel': 9, 'tipo': 'Normal', 'subtipo': 'Volador'}]},
    {'nombre': 'Bugsy', 'torneos_ganados': 1, 'batallas_perdidas': 35, 'batallas_ganadas': 90, 'pokemons': [{'nombre': 'Metapod', 'nivel': 14, 'tipo': 'Bicho', 'subtipo': None}, {'nombre': 'Kakuna', 'nivel': 14, 'tipo': 'Bicho', 'subtipo': 'Veneno'}, {'nombre': 'Scyther', 'nivel': 16, 'tipo': 'Bicho', 'subtipo': 'Volador'}]},
    {'nombre': 'Whitney', 'torneos_ganados': 2, 'batallas_perdidas': 25, 'batallas_ganadas': 110, 'pokemons': [{'nombre': 'Clefairy', 'nivel': 18, 'tipo': 'Hada', 'subtipo': None}, {'nombre': 'Miltank', 'nivel': 20, 'tipo': 'Normal', 'subtipo': None}]},
    {'nombre': 'Morty', 'torneos_ganados': 2, 'batallas_perdidas': 30, 'batallas_ganadas': 120, 'pokemons': [{'nombre': 'Gastly', 'nivel': 21, 'tipo': 'Fantasma', 'subtipo': 'Veneno'}, {'nombre': 'Haunter', 'nivel': 21, 'tipo': 'Fantasma', 'subtipo': 'Veneno'}, {'nombre': 'Haunter', 'nivel': 23, 'tipo': 'Fantasma', 'subtipo': 'Veneno'}, {'nombre': 'Gengar', 'nivel': 25, 'tipo': 'Fantasma', 'subtipo': 'Veneno'}]},
    {'nombre': 'Chuck', 'torneos_ganados': 2, 'batallas_perdidas': 45, 'batallas_ganadas': 100, 'pokemons': [{'nombre': 'Primeape', 'nivel': 27, 'tipo': 'Lucha', 'subtipo': None}, {'nombre': 'Poliwrath', 'nivel': 30, 'tipo': 'Agua', 'subtipo': 'Lucha'}]},
    {'nombre': 'Jasmine', 'torneos_ganados': 3, 'batallas_perdidas': 25, 'batallas_ganadas': 135, 'pokemons': [{'nombre': 'Magnemite', 'nivel': 30, 'tipo': 'Eléctrico', 'subtipo': 'Acero'}, {'nombre': 'Magnemite', 'nivel': 30, 'tipo': 'Eléctrico', 'subtipo': 'Acero'}, {'nombre': 'Steelix', 'nivel': 35, 'tipo': 'Acero', 'subtipo': 'Tierra'}]},
    {'nombre': 'Pryce', 'torneos_ganados': 4, 'batallas_perdidas': 50, 'batallas_ganadas': 160, 'pokemons': [{'nombre': 'Seel', 'nivel': 27, 'tipo': 'Agua', 'subtipo': None}, {'nombre': 'Dewgong', 'nivel': 29, 'tipo': 'Agua', 'subtipo': 'Hielo'}, {'nombre': 'Piloswine', 'nivel': 31, 'tipo': 'Hielo', 'subtipo': 'Tierra'}]},
    {'nombre': 'Clair', 'torneos_ganados': 4, 'batallas_perdidas': 30, 'batallas_ganadas': 180, 'pokemons': [{'nombre': 'Dragonair', 'nivel': 37, 'tipo': 'Dragón', 'subtipo': None}, {'nombre': 'Dragonair', 'nivel': 37, 'tipo': 'Dragón', 'subtipo': None}, {'nombre': 'Gyarados', 'nivel': 38, 'tipo': 'Agua', 'subtipo': 'Volador'}, {'nombre': 'Kingdra', 'nivel': 40, 'tipo': 'Agua', 'subtipo': 'Dragón'}]},
    {'nombre': 'Lance', 'torneos_ganados': 6, 'batallas_perdidas': 20, 'batallas_ganadas': 280, 'pokemons': [{'nombre': 'Gyarados', 'nivel': 44, 'tipo': 'Agua', 'subtipo': 'Volador'}, {'nombre': 'Dragonite', 'nivel': 47, 'tipo': 'Dragón', 'subtipo': 'Volador'}, {'nombre': 'Dragonite', 'nivel': 47, 'tipo': 'Dragón', 'subtipo': 'Volador'}, {'nombre': 'Dragonite', 'nivel': 50, 'tipo': 'Dragón', 'subtipo': 'Volador'}, {'nombre': 'Aerodactyl', 'nivel': 46, 'tipo': 'Roca', 'subtipo': 'Volador'}, {'nombre': 'Charizard', 'nivel': 46, 'tipo': 'Fuego', 'subtipo': 'Volador'}]},
    
    # --- HOENN ---
    {'nombre': 'Roxanne', 'torneos_ganados': 1, 'batallas_perdidas': 30, 'batallas_ganadas': 70, 'pokemons': [{'nombre': 'Geodude', 'nivel': 14, 'tipo': 'Roca', 'subtipo': 'Tierra'}, {'nombre': 'Nosepass', 'nivel': 15, 'tipo': 'Roca', 'subtipo': None}]},
    {'nombre': 'Brawly', 'torneos_ganados': 1, 'batallas_perdidas': 35, 'batallas_ganadas': 85, 'pokemons': [{'nombre': 'Machop', 'nivel': 17, 'tipo': 'Lucha', 'subtipo': None}, {'nombre': 'Makuhita', 'nivel': 18, 'tipo': 'Lucha', 'subtipo': None}, {'nombre': 'Terrakion', 'nivel': 50, 'tipo': 'Roca', 'subtipo': 'Lucha'}]},
    {'nombre': 'Wattson', 'torneos_ganados': 2, 'batallas_perdidas': 40, 'batallas_ganadas': 110, 'pokemons': [{'nombre': 'Voltorb', 'nivel': 20, 'tipo': 'Eléctrico', 'subtipo': None}, {'nombre': 'Electrike', 'nivel': 20, 'tipo': 'Eléctrico', 'subtipo': None}, {'nombre': 'Magneton', 'nivel': 22, 'tipo': 'Eléctrico', 'subtipo': 'Acero'}, {'nombre': 'Manectric', 'nivel': 24, 'tipo': 'Eléctrico', 'subtipo': None}]},
    {'nombre': 'Flannery', 'torneos_ganados': 2, 'batallas_perdidas': 25, 'batallas_ganadas': 125, 'pokemons': [{'nombre': 'Numel', 'nivel': 26, 'tipo': 'Fuego', 'subtipo': 'Tierra'}, {'nombre': 'Slugma', 'nivel': 26, 'tipo': 'Fuego', 'subtipo': None}, {'nombre': 'Camerupt', 'nivel': 28, 'tipo': 'Fuego', 'subtipo': 'Tierra'}, {'nombre': 'Torkoal', 'nivel': 29, 'tipo': 'Fuego', 'subtipo': None}]},
    {'nombre': 'Norman', 'torneos_ganados': 3, 'batallas_perdidas': 30, 'batallas_ganadas': 160, 'pokemons': [{'nombre': 'Slaking', 'nivel': 27, 'tipo': 'Normal', 'subtipo': None}, {'nombre': 'Vigoroth', 'nivel': 30, 'tipo': 'Normal', 'subtipo': None}, {'nombre': 'Slaking', 'nivel': 31, 'tipo': 'Normal', 'subtipo': None}]},
    {'nombre': 'Winona', 'torneos_ganados': 3, 'batallas_perdidas': 20, 'batallas_ganadas': 140, 'pokemons': [{'nombre': 'Swablu', 'nivel': 29, 'tipo': 'Normal', 'subtipo': 'Volador'}, {'nombre': 'Tropius', 'nivel': 29, 'tipo': 'Planta', 'subtipo': 'Volador'}, {'nombre': 'Pelipper', 'nivel': 30, 'tipo': 'Agua', 'subtipo': 'Volador'}, {'nombre': 'Skarmory', 'nivel': 31, 'tipo': 'Acero', 'subtipo': 'Volador'}, {'nombre': 'Altaria', 'nivel': 33, 'tipo': 'Dragón', 'subtipo': 'Volador'}, {'nombre': 'Wingull', 'nivel': 25, 'tipo': 'Agua', 'subtipo': 'Volador'}]},
    {'nombre': 'Tate', 'torneos_ganados': 2, 'batallas_perdidas': 15, 'batallas_ganadas': 115, 'pokemons': [{'nombre': 'Claydol', 'nivel': 41, 'tipo': 'Tierra', 'subtipo': 'Psíquico'}, {'nombre': 'Xatu', 'nivel': 41, 'tipo': 'Psíquico', 'subtipo': 'Volador'}, {'nombre': 'Lunatone', 'nivel': 42, 'tipo': 'Roca', 'subtipo': 'Psíquico'}, {'nombre': 'Solrock', 'nivel': 42, 'tipo': 'Roca', 'subtipo': 'Psíquico'}]},
    {'nombre': 'Wallace', 'torneos_ganados': 5, 'batallas_perdidas': 25, 'batallas_ganadas': 210, 'pokemons': [{'nombre': 'Wailord', 'nivel': 57, 'tipo': 'Agua', 'subtipo': None}, {'nombre': 'Tentacruel', 'nivel': 55, 'tipo': 'Agua', 'subtipo': 'Veneno'}, {'nombre': 'Ludicolo', 'nivel': 56, 'tipo': 'Agua', 'subtipo': 'Planta'}, {'nombre': 'Whiscash', 'nivel': 56, 'tipo': 'Agua', 'subtipo': 'Tierra'}, {'nombre': 'Gyarados', 'nivel': 56, 'tipo': 'Agua', 'subtipo': 'Volador'}, {'nombre': 'Milotic', 'nivel': 58, 'tipo': 'Agua', 'subtipo': None}]},
    {'nombre': 'Steven', 'torneos_ganados': 5, 'batallas_perdidas': 10, 'batallas_ganadas': 290, 'pokemons': [{'nombre': 'Skarmory', 'nivel': 57, 'tipo': 'Acero', 'subtipo': 'Volador'}, {'nombre': 'Claydol', 'nivel': 55, 'tipo': 'Tierra', 'subtipo': 'Psíquico'}, {'nombre': 'Aggron', 'nivel': 56, 'tipo': 'Acero', 'subtipo': 'Roca'}, {'nombre': 'Cradily', 'nivel': 56, 'tipo': 'Roca', 'subtipo': 'Planta'}, {'nombre': 'Armaldo', 'nivel': 56, 'tipo': 'Roca', 'subtipo': 'Bicho'}, {'nombre': 'Metagross', 'nivel': 58, 'tipo': 'Acero', 'subtipo': 'Psíquico'}, {'nombre': 'Tyrantrum', 'nivel': 60, 'tipo': 'Roca', 'subtipo': 'Dragón'}]},

    # --- OTRAS REGIONES (Expansión) ---
    {'nombre': 'Cynthia', 'torneos_ganados': 8, 'batallas_perdidas': 5, 'batallas_ganadas': 320, 'pokemons': [{'nombre': 'Spiritomb', 'nivel': 61, 'tipo': 'Fantasma', 'subtipo': 'Siniestro'}, {'nombre': 'Garchomp', 'nivel': 66, 'tipo': 'Dragón', 'subtipo': 'Tierra'}, {'nombre': 'Lucario', 'nivel': 63, 'tipo': 'Lucha', 'subtipo': 'Acero'}, {'nombre': 'Milotic', 'nivel': 63, 'tipo': 'Agua', 'subtipo': None}]},
    {'nombre': 'Nemona', 'torneos_ganados': 3, 'batallas_perdidas': 15, 'batallas_ganadas': 150, 'pokemons': [{'nombre': 'Scovillain', 'nivel': 55, 'tipo': 'Fuego', 'subtipo': 'Planta'}, {'nombre': 'Pawmot', 'nivel': 56, 'tipo': 'Eléctrico', 'subtipo': 'Lucha'}, {'nombre': 'Quaquaval', 'nivel': 57, 'tipo': 'Agua', 'subtipo': 'Lucha'}]},
    {'nombre': 'Elesa', 'torneos_ganados': 2, 'batallas_perdidas': 20, 'batallas_ganadas': 95, 'pokemons': [{'nombre': 'Emolga', 'nivel': 27, 'tipo': 'Eléctrico', 'subtipo': 'Volador'}, {'nombre': 'Emolga', 'nivel': 27, 'tipo': 'Eléctrico', 'subtipo': 'Volador'}, {'nombre': 'Zebstrika', 'nivel': 29, 'tipo': 'Eléctrico', 'subtipo': None}]}
]
