superheroes = [
    {'nombre': 'Linterna Verde', 'año_aparicion': 1940, 'casa_comic': 'DC', 'biografia': 'Portador del anillo de poder intergaláctico.'},
    {'nombre': 'Wolverine', 'año_aparicion': 1974, 'casa_comic': 'Marvel', 'biografia': 'Mutante con factor de curación y esqueleto de adamantium.'},
    {'nombre': 'Dr. Strange', 'año_aparicion': 1963, 'casa_comic': 'DC', 'biografia': 'Hechicero supremo, maestro de las artes místicas.'},
    {'nombre': 'Iron Man', 'año_aparicion': 1963, 'casa_comic': 'Marvel', 'biografia': 'Multimillonario que usa una armadura de alta tecnología para combatir el mal.'},
    {'nombre': 'Batman', 'año_aparicion': 1939, 'casa_comic': 'DC', 'biografia': 'Lucha contra el crimen con un traje murciélago especial y muchos gadgets.'},
    {'nombre': 'Superman', 'año_aparicion': 1938, 'casa_comic': 'DC', 'biografia': 'El hombre de acero, proveniente de Krypton.'},
    {'nombre': 'Spider-Man', 'año_aparicion': 1962, 'casa_comic': 'Marvel', 'biografia': 'Usa un traje rojo y azul, lanza telarañas y tiene sentido arácnido.'},
    {'nombre': 'Capitana Marvel', 'año_aparicion': 1967, 'casa_comic': 'Marvel', 'biografia': 'Posee poderes cósmicos y puede volar por el espacio.'},
    {'nombre': 'Mujer Maravilla', 'año_aparicion': 1941, 'casa_comic': 'DC', 'biografia': 'Princesa amazona, guerrera con el lazo de la verdad.'},
    {'nombre': 'Flash', 'año_aparicion': 1940, 'casa_comic': 'DC', 'biografia': 'El hombre más rápido vivo, conectado a la fuerza de la velocidad.'},
    {'nombre': 'Star-Lord', 'año_aparicion': 1976, 'casa_comic': 'Marvel', 'biografia': 'Líder de los guardianes de la galaxia, explorador espacial.'},
    {'nombre': 'Bruja Escarlata', 'año_aparicion': 1964, 'casa_comic': 'Marvel', 'biografia': 'Mutante con habilidades para alterar la realidad.'},
    {'nombre': 'Batgirl', 'año_aparicion': 1961, 'casa_comic': 'DC', 'biografia': 'Lucha contra el crimen en Gotham con un traje y habilidades de detective.'},
    {'nombre': 'Blue Beetle', 'año_aparicion': 1939, 'casa_comic': 'DC', 'biografia': 'Utiliza una armadura escarabajo alienígena.'},
    {'nombre': 'Mr. Fantástico', 'año_aparicion': 1961, 'casa_comic': 'Marvel', 'biografia': 'Líder de los Cuatro Fantásticos, cuerpo elástico.'},
    {'nombre': 'Thor', 'año_aparicion': 1962, 'casa_comic': 'Marvel', 'biografia': 'Dios del trueno asgardiano con su martillo Mjolnir.'},
    {'nombre': 'Hulk', 'año_aparicion': 1962, 'casa_comic': 'Marvel', 'biografia': 'Científico que se transforma en un monstruo verde por la radiación gamma.'},
    {'nombre': 'Viuda Negra', 'año_aparicion': 1964, 'casa_comic': 'Marvel', 'biografia': 'Espía experta y combatiente cuerpo a cuerpo de primer nivel.'},
    {'nombre': 'Ojo de Halcón', 'año_aparicion': 1964, 'casa_comic': 'Marvel', 'biografia': 'Maestro arquero sin superpoderes pero letal con el arco.'},
    {'nombre': 'Capitán América', 'año_aparicion': 1941, 'casa_comic': 'Marvel', 'biografia': 'Súper soldado de la Segunda Guerra Mundial, usa un traje estrellado y escudo.'},
    {'nombre': 'Pantera Negra', 'año_aparicion': 1966, 'casa_comic': 'Marvel', 'biografia': 'Rey de Wakanda, su armadura de vibranium lo protege.'},
    {'nombre': 'Ant-Man', 'año_aparicion': 1962, 'casa_comic': 'Marvel', 'biografia': 'Puede encogerse al tamaño de una hormiga gracias a su traje especial.'},
    {'nombre': 'Avispa', 'año_aparicion': 1963, 'casa_comic': 'Marvel', 'biografia': 'Heroína capaz de encogerse y volar con alas bio-sintéticas.'},
    {'nombre': 'Aquaman', 'año_aparicion': 1941, 'casa_comic': 'DC', 'biografia': 'Rey de Atlantis, puede comunicarse con la vida marina.'},
    {'nombre': 'Cyborg', 'año_aparicion': 1980, 'casa_comic': 'DC', 'biografia': 'Parte hombre, parte máquina con armadura cibernética integrada.'},
    {'nombre': 'Shazam', 'año_aparicion': 1939, 'casa_comic': 'DC', 'biografia': 'Niño que al decir una palabra mágica adquiere poderes de los dioses.'},
    {'nombre': 'Flecha Verde', 'año_aparicion': 1941, 'casa_comic': 'DC', 'biografia': 'Arquero de Star City, multimillonario convertido en justiciero.'},
    {'nombre': 'Detective Marciano', 'año_aparicion': 1955, 'casa_comic': 'DC', 'biografia': 'Último sobreviviente de Marte, con fuerza y telepatía.'},
    {'nombre': 'Supergirl', 'año_aparicion': 1959, 'casa_comic': 'DC', 'biografia': 'Prima de Superman con sus mismos poderes y debilidades.'},
    {'nombre': 'Nightwing', 'año_aparicion': 1984, 'casa_comic': 'DC', 'biografia': 'El primer Robin de Batman, ahora un héroe independiente.'},
    {'nombre': 'Daredevil', 'año_aparicion': 1964, 'casa_comic': 'Marvel', 'biografia': 'Abogado ciego con sentidos aumentados que protege Hell\'s Kitchen.'},
    {'nombre': 'Punisher', 'año_aparicion': 1974, 'casa_comic': 'Marvel', 'biografia': 'Antihéroe militar que usa un traje con una calavera.'},
    {'nombre': 'Ghost Rider', 'año_aparicion': 1972, 'casa_comic': 'Marvel', 'biografia': 'El espíritu de la venganza montado en motocicleta flamígera.'},
    {'nombre': 'Blade', 'año_aparicion': 1973, 'casa_comic': 'Marvel', 'biografia': 'Cazador de vampiros, mitad humano y mitad vampiro. Su armadura lo protege.'},
    {'nombre': 'Silver Surfer', 'año_aparicion': 1966, 'casa_comic': 'Marvel', 'biografia': 'Heraldo de Galactus, viaja por el espacio en una tabla.'},
    {'nombre': 'Cíclope', 'año_aparicion': 1963, 'casa_comic': 'Marvel', 'biografia': 'Líder de los X-Men, dispara rayos ópticos destructivos.'},
    {'nombre': 'Jean Grey', 'año_aparicion': 1963, 'casa_comic': 'Marvel', 'biografia': 'Poderosa mutante telepática y telequinética, unida a la Fuerza Fénix.'},
    {'nombre': 'Tormenta', 'año_aparicion': 1975, 'casa_comic': 'Marvel', 'biografia': 'Mutante capaz de controlar el clima a su voluntad.'},
    {'nombre': 'Bestia', 'año_aparicion': 1963, 'casa_comic': 'Marvel', 'biografia': 'Mutante de pelo azul con fuerza sobrehumana y mente brillante.'},
    {'nombre': 'Gambito', 'año_aparicion': 1990, 'casa_comic': 'Marvel', 'biografia': 'Mutante que carga energía cinética en objetos, como cartas de póker.'},
    {'nombre': 'Rogue', 'año_aparicion': 1981, 'casa_comic': 'Marvel', 'biografia': 'Absorbe poderes y memorias a través del contacto físico.'},
    {'nombre': 'Profesor X', 'año_aparicion': 1963, 'casa_comic': 'Marvel', 'biografia': 'Fundador de los X-Men, el telépata más poderoso del mundo.'},
    {'nombre': 'Magneto', 'año_aparicion': 1963, 'casa_comic': 'Marvel', 'biografia': 'Maestro del magnetismo, antiguo villano y aliado de los X-Men.'},
    {'nombre': 'Loki', 'año_aparicion': 1962, 'casa_comic': 'Marvel', 'biografia': 'Dios de las mentiras, a menudo villano pero a veces salvador.'},
    {'nombre': 'Thanos', 'año_aparicion': 1973, 'casa_comic': 'Marvel', 'biografia': 'El Titán Loco, obsesionado con equilibrar el universo.'},
    {'nombre': 'Deadpool', 'año_aparicion': 1991, 'casa_comic': 'Marvel', 'biografia': 'El mercenario bocazas con factor de curación extremo. Usa un traje rojo.'},
    {'nombre': 'Cable', 'año_aparicion': 1990, 'casa_comic': 'Marvel', 'biografia': 'Mutante viajero del tiempo con un brazo cibernético.'},
    {'nombre': 'Groot', 'año_aparicion': 1960, 'casa_comic': 'Marvel', 'biografia': 'Árbol humanoide alienígena, miembro de los Guardianes de la Galaxia.'},
    {'nombre': 'Rocket Raccoon', 'año_aparicion': 1976, 'casa_comic': 'Marvel', 'biografia': 'Mapache modificado genéticamente, experto en armas y explosivos.'},
    {'nombre': 'Drax', 'año_aparicion': 1973, 'casa_comic': 'Marvel', 'biografia': 'Guerrero fiero creado para destruir a Thanos.'},
    {'nombre': 'Gamora', 'año_aparicion': 1975, 'casa_comic': 'Marvel', 'biografia': 'La mujer más letal de la galaxia e hija adoptiva de Thanos.'},
    {'nombre': 'Nova', 'año_aparicion': 1976, 'casa_comic': 'Marvel', 'biografia': 'Miembro de los Nova Corps, la policía intergaláctica.'},
    {'nombre': 'Adam Warlock', 'año_aparicion': 1967, 'casa_comic': 'Marvel', 'biografia': 'Ser artificial creado para ser la evolución humana perfecta.'},
    {'nombre': 'Bucky Barnes', 'año_aparicion': 1941, 'casa_comic': 'Marvel', 'biografia': 'Amigo del Capitán América, convertido en el Soldado del Invierno.'},
    {'nombre': 'Falcon', 'año_aparicion': 1969, 'casa_comic': 'Marvel', 'biografia': 'Héroe alado y frecuente compañero del Capitán América.'},
    {'nombre': 'Robin', 'año_aparicion': 1940, 'casa_comic': 'DC', 'biografia': 'El joven maravilla, inseparable compañero de Batman.'},
    {'nombre': 'Red Hood', 'año_aparicion': 2005, 'casa_comic': 'DC', 'biografia': 'Jason Todd resucitado, usa métodos letales contra los criminales.'},
    {'nombre': 'Raven', 'año_aparicion': 1980, 'casa_comic': 'DC', 'biografia': 'Hija de un demonio, usa magia empática oscura.'},
    {'nombre': 'Starfire', 'año_aparicion': 1980, 'casa_comic': 'DC', 'biografia': 'Princesa alienígena de Tamaran, dispara rayos de energía.'},
    {'nombre': 'Beast Boy', 'año_aparicion': 1965, 'casa_comic': 'DC', 'biografia': 'Héroe de piel verde que puede transformarse en cualquier animal.'},
]